/*
 * global_object.c
 *
 *  Created on: Nov 1, 2022
 *      Author: ntpt
 */

#include "User/global_object.h"

const uint32_t LED_BLINK_PERIOD_MS = 1000;
const uint32_t BUTTON_LONG_PRESS_DELAY_MS = 3000;
const uint32_t BUTTON_LONG_PRESS_REACTIVATE_PERIOD_MS = 1000;
const uint32_t NO_ACTION_AUTO_DECREMENT_DELAY_MS = 10000;

volatile Software_timer_t timer_10s =
{ 0, TIMER_FLAG_RESET, };
volatile Software_timer_t led_blink =
{ 0, TIMER_FLAG_RESET, };

volatile Button_t button_reset =
{
	.FILTER_DELAY_COUNT_MAX = 3,
	.HOLD_STATE_DELAY_COUNT_MAX =
			BUTTON_LONG_PRESS_DELAY_MS / TIMER_TICK_DURATION_MS,
	.HOLD_STATE_ACTIVATE_COUNT_MAX =
			BUTTON_LONG_PRESS_REACTIVATE_PERIOD_MS / TIMER_TICK_DURATION_MS,
	.READING_WHEN_PRESSED = GPIO_PIN_RESET,
	.PIN = BT_RESET_Pin,
	.PORT = BT_RESET_GPIO_Port,
};
volatile Button_t button_inc =
{
	.FILTER_DELAY_COUNT_MAX = 3,
	.HOLD_STATE_DELAY_COUNT_MAX =
			BUTTON_LONG_PRESS_DELAY_MS / TIMER_TICK_DURATION_MS,
	.HOLD_STATE_ACTIVATE_COUNT_MAX =
			BUTTON_LONG_PRESS_REACTIVATE_PERIOD_MS / TIMER_TICK_DURATION_MS,
	.READING_WHEN_PRESSED = GPIO_PIN_RESET,
	.PIN = BT_INC_Pin,
	.PORT = BT_INC_GPIO_Port,
};
volatile Button_t button_dec =
{
	.FILTER_DELAY_COUNT_MAX = 3,
	.HOLD_STATE_DELAY_COUNT_MAX =
			BUTTON_LONG_PRESS_DELAY_MS / TIMER_TICK_DURATION_MS,
	.HOLD_STATE_ACTIVATE_COUNT_MAX =
			BUTTON_LONG_PRESS_REACTIVATE_PERIOD_MS / TIMER_TICK_DURATION_MS,
	.READING_WHEN_PRESSED = GPIO_PIN_RESET,
	.PIN = BT_DEC_Pin,
	.PORT = BT_DEC_GPIO_Port,
};

FSM_t fsm_count =
{ .current_state = STATE_0, };

uint8_t current_count = 0;
